services:
  edge_service:
    image: transcoding-env:latest
    container_name: transcoding_container
    privileged: true
    volumes:
      - /dev/bus/usb:/dev/bus/usb
      - /dev:/dev
    network_mode: host
    cpuset: "0-5"
    mem_reservation: 16G
    mem_limit: 24G 
    restart: always
    command: tail -f /dev/null